---
- hosts: all
  gather_facts: true
  roles:
    - { role: network/vrack-ifup, tags: vrack-ifup }
    - { role: network/firewall, tags: firewall }
    - { role: bind9/preinstall, tags: bind9-preinstall }

- hosts: masters
  gather_facts: false
  roles:
    - { role: bind9/masters/rndc, tags: bind9-masters-rndc }
    - { role: bind9/masters/config, tags: bind9-masters-cfg }

- hosts: slaves
  gather_facts: false
  roles:
    - { role: bind9/slaves/config, tags: bind9-slaves-cfg }

- hosts: masters
  gather_facts: false
  roles:
    - { role: bind9/masters/check, tags: bind9-masters-check }

- hosts: slaves
  gather_facts: false
  roles:
    - { role: bind9/slaves/check, tags: bind9-slaves-check }

- hosts: all
  gather_facts: false
  roles:
    - { role: bind9/monitoring, tags: bind9-monitoring }
