---
- name: create folder /var/cache/bind/data
  file:
    path: /var/cache/bind/data
    state: directory

- name: template named config
  template:
    src: ./named.conf.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
  notify:
  - bind9-restart
